# -*- coding: utf-8 -*-
"""Red Wine EDAcleaned.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qIIHeJ97irQKciy2APoAPgC6q2ljsYou

The primary purpose of the actions taken in this notebook is to understand and prepare the wine quality dataset for further analysis or machine learning tasks.

In this notebook explored the dataset's basic characteristics: Head, shape, data types, and descriptive statistics.
Identified and handled data quality issues: Checked for missing values (none found) and removed duplicate records.
Performed initial exploratory data analysis (EDA): Examined the distribution of the 'quality' variable and other features using bar plots and histograms. Visualized relationships and correlations between variables using heatmaps, catplots, and scatter plots.
"""

import pandas as pd
df = pd.read_csv('red.csv',sep = ';')
df.head()

df.shape

## Sumamry of the dataset
df.info()

## Descriptive statistics
df.describe()

## Shape of the dataset
df.shape

## List down the columns
df.columns

df.values

df.index

df['quality'].unique()

# Conclusion --> Imbalanced dataset
df['quality'].value_counts()

## Missing values
df.isnull().sum()

df.duplicated()

## Check duplicate records
df[df.duplicated()]

## Remove duplicate records
df.drop_duplicates(inplace=True)

df.shape

df.corr()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 6))
sns.heatmap(df.corr(), annot=True, fmt='.2f')

df['quality'].value_counts().plot(kind='bar')

sns.histplot(df['fixed acidity'], kde=True)

df.columns

for i in df.columns:
    sns.histplot(df[i], kde=True)
    plt.title(i)
    plt.show()

## Catetgorical plot
sns.catplot(x='quality', y='alcohol', data=df, kind='box')

sns.scatterplot(x='alcohol', y='pH', style='quality', data=df)

df.head()

sns.scatterplot(x='chlorides', y='density', style='quality', data=df)